FROM nvcr.io/nvidia/tensorflow:17.04

RUN apt-get update && \
    apt-get install -y python-tk && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN mkdir -p /workspace
WORKDIR /workspace

COPY ./requirements.txt /workspace/requirements.txt
RUN pip install -r requirements.txt

COPY . /workspace

CMD ./entrypoint.sh

